title: Urban Memory
theme: ["PaperMod"]

params:
  profileMode:
    enabled: true
    title: "urban memory" # optional default will be site title
    subtitle: "welcome to memory"
    imageUrl: "<image link>" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Archive
        url: ""
      - name: Tags
        url: ""

  socialIcons: 
    - name: "github"
      url: "https://github.com/dinanabila"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/dinanabila/"