title: urban memory
theme: ["PaperMod"]

params:
  profileMode:
    enabled: true
    title: "hai!" 
    subtitle: "selamat menjelajah :D"
    imageUrl: "/static/image/icons8-cave-100.png" 
    imageTitle: "ikon" 
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Arsip
        url: ""
      - name: Tags
        url: ""
      - name: Panduan
        url: ""

  socialIcons: 
    - name: "github"
      url: "https://github.com/dinanabila"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/dinanabila/"