title: goa grafik
theme: ["PaperMod"]

params:
  profileMode:
    enabled: true
    title: "hai!" 
    subtitle: "selamat menjelajah :D"
    imageUrl: "https://github.com/dinanabila/goa-grafik/blob/main/static/image/icons8-cave-100.png?raw=true"
    imageTitle: "" 
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Arsip
        url: ""
      - name: Tags
        url: ""
      - name: Panduan
        url: ""

  socialIcons: 
    - name: "github"
      url: "https://github.com/dinanabila"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/dinanabila/"